# Generated by Django 2.0.4 on 2018-04-27 15:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Administrative Entity name', max_length=163)),
                ('insee', models.CharField(help_text='Insee Code', max_length=5, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(default=None, editable=False, spatial_index=False, srid=3857)),
            ],
        ),
        migrations.CreateModel(
            name='ZIPCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(help_text='Zip Code', max_length=5)),
                ('insee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoinsee.AdministrativeEntity')),
            ],
        ),
    ]
